### ISSUE TITLE
On Firefox all "Page last updated:" slugs appear as "Page last updated: Invalid Date NaN, NaN"

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/docs-cf-cli#1]
It looks like the updated date/time is inserted by this code: `<span data-behavior="DisplayModifiedDate" data-modified-date="2016-03-04 00:37:53 UTC">`

Firefox renders it as `Invalid Date NaN, NaN`, Chrome as `March 3, 2016`. The MDN docs for a string arg for "new Date()" state that the arg "should be in a format recognized by the Date.parse() method (IETF-compliant RFC 2822 timestamps and also a version of ISO8601)." The ECMA script specifies this at http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15: 
```
ECMAScript defines a string interchange format for date-times based upon a simplification of the ISO 8601 Extended Format. The format is as follows: YYYY-MM-DDTHH:mm:ss.sssZ
```
The " UTC" suffix is not supported in the ECMA spec nor by RFC 2822. I used the Chrome console to demonstrate that `...Z` works just as well as `... UTC`.

**Comment by animatedmax** [comment]
Hi @ericpromislow -- We have reported this bug to our developers. Thank you for raising this issue!

**Comment by animatedmax** [comment]
@ericpromislow This issue should now be resolved. Thanks again.
