### ISSUE TITLE
cf command prompt is disappearing

### ISSUE THREAD

**Issue by Gurpret7** [cloudfoundry/docs-cf-cli#17]
When I am running cf command prompt after installing cf Command Line Interface, it appears for 2 sec and then suddenly disappears.
Can you pls help me on this.

Thanks!!

**Comment by bentarnoff** [comment]
Hey @Gurpret7 thanks for this. Please join the Cloud Foundry Slack at https://slack.cloudfoundry.org/ and then join the #cli channel. If you provide a bit more information about your issue, they should be able to help. I'm closing this issue but feel free to re-open if you have any further questions. Thank you.
