### ISSUE TITLE
CLI HTTP Proxy document not mention http_proxy

### ISSUE THREAD

**Issue by wangf1** [cloudfoundry/docs-cf-cli#24]
[Using the cf CLI with an HTTP Proxy Server](https://github.com/cloudfoundry/docs-cf-cli/blob/master/http-proxy.html.md.erb) document only mentions https_proxy environment variable but not mention **http_proxy**.
While I found "cf logs [app name]" command will use http_proxy. If I do not set http_proxy, logs command will fail to connect log service, with following error:

> C:\>cf logs worker-app
> FAILED
> Timed out waiting for connection to Loggregator (wss://***.com:443).

**Comment by ljarzynski** [comment]
Thanks for filing this issue @wangf1 !

@dkoper -- Would appreciate your input on this. Should we mention on this page that users need to set http_proxy to be able to use the cf logs command?

**Comment by dkoper** [comment]
@wangf1 Thanks for letting us know! It seems I have both environment variables enabled in my system so never noticed this.

@ljarzynski Can you move the tracker story, or a clone of it, into the CLI icebox?
We should make it work with `https_proxy`.

**Comment by ljarzynski** [comment]
Thanks @dkoper! Just moved the story over.

**Comment by dkoper** [comment]
This has been fixed in cf CLI 6.26.0. Thanks again for bringing it to my attention!
