### ISSUE TITLE
80/443 ports closed on API?

### ISSUE THREAD

**Issue by frantisek121** [cloudfoundry/docs-cf-cli#3]
Hi,

I am trying to run cloudfoundry on openstack. I have used command "bosh-init deploy ./bosh.yml" (https://bosh.io/docs/init-openstack.html) and I got vm running. So I would like to continue with Deploying and Developing PHP Apps (http://docs.cloudfoundry.org/buildpacks/php/gsg-php-usage.html). That got me here - Installing the cf Command Line Interface (http://docs.cloudfoundry.org/cf-cli/install-go-cli.html) and from there here - Getting Started with the cf CLI (http://docs.cloudfoundry.org/cf-cli/getting-started.html). 

Now I got stucked on command "cf login -a https://api.test.com --skip-ssl-validation"

Error performing request: Get https://api.test.com/v2/info: dial tcp <FIP of vm created by bosh.yml>:443: getsockopt: connection refused.

I assume that the API IP is the FIP of vm that was created by "bosh-init deploy ./bosh.yml". I have checked the vm and ports 80 and 443 are not open. I have checked network/fw with "nc -l 80" and "nc -l 443", can curl them with no problem.

So, am I doing something wrong, or am I just lost in documentation?

Thank you

Br

Frantisek

**Comment by bentarnoff** [comment]
Thanks, @frantisek121!

We recommend bringing your question to the Cloud Foundry cf-dev mailing list (cf-dev@lists.cloudfoundry.org), searching its archives (https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/), or joining the Cloud Foundry Slack channel (https://slack.cloudfoundry.org/). We are closing this issue for now but please let us know if you feel the documentation needs to be updated after you have resolved your problem.
