### ISSUE TITLE
New feature: request

### ISSUE THREAD

**Issue by SnehaKumari22** [cloudfoundry/docs-cf-cli#41]
The command for creating a new org and space adds the user creating it as org manager and space manager and developer respectively. Can an option be included to the command to prevent this so that only the org or space gets created without the user getting aligned to it as it takes three command to unset the roles later. Thanks.

**Comment by seviet** [comment]
Hi @SnehaKumari22 -- I am forwarding this feature request to the CLI PMs @dkoper  and @jbpivotal. This is the repo for the CLI docs. @dkoper @jbpivotal if you can acknowledge this request, I can close this out since it is not a doc issue.

**Comment by seviet** [comment]
Hey @SnehaKumari22 -- if you have not heard back from @dkoper yet, I would also try making your request to the #cli channel on cloudfoundry.slack.com. closing this.
