### ISSUE TITLE
Installing the cf CLI

### ISSUE THREAD

**Issue by LeoCYang** [cloudfoundry/docs-cf-cli#49]
In the CLI installation page Mac OS X Installation section 
https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#pkg-mac

The command to Install the cf CLI should change from 
"brew install cf-cli"
to 
"brew install cloudfoundry/tap/cf-cli"

I have tested it on my Mac to verify the command.

**Comment by quixoticmonk** [comment]
The change is already incorporated into the documentation. This issue should be closed.
https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#pkg-mac .

**Comment by jncd** [comment]
@LeoCYang : Thank you for logging this issue. 

@quixoticmonk : Thanks so much for pointing this out. I'm closing this issue.
