### ISSUE TITLE
CF LOGIN Proxy issue

### ISSUE THREAD

**Issue by sanjaykm007** [cloudfoundry/docs-cf-cli#54]
I m new to PCF environment and using below command to login
cf login -a api.run.pivotal.io

and I am getting below error

C:\Cloud Foundry>cf login
API endpoint: api.run.pivotal.io

Request error: Get https://api.run.pivotal.io: authenticationrequired
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED

My proxy (https_proxy env variable) is set as : -http://user:password@proxy:3128
also tried without username/password in proxy with no luck.

CF version is -  6.47

Pls suggest

**Comment by mlimonczenko** [comment]
Hello @sanjaykm007.
We don't help with troubleshooting issues like these, as our focus is just the documentation. If you are using PCF, perhaps try contacting support: https://support.pivotal.io.
