### ISSUE TITLE
cf7 Release Timeline

### ISSUE THREAD

**Issue by james-flynn-ie** [cloudfoundry/docs-cf-cli#55]
Hello

We are looking to migrate to cf7 in a production environment due to those pesky deprecation warnings. Would you happen to know when cf7 will exit beta?

Apologies for posting here, but I was unable to find anywhere else to ask.

**Comment by jncd** [comment]
Hello @james-flynn-ie (James), 
We (regular contributors to CF docs) don't have any special insight into the date of the cf7 release. 
However, you should be able to view their Tracker and watch the progress: https://www.pivotaltracker.com/n/projects/2196383 . 
I hope this helps.
