### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by jason-upchurch** [cloudfoundry/docs-cf-cli#68]
### Summary
When reviewing the cloudfoundry documentation about buildpacks, I attempted to click on the "buildpacks" link

### Steps to reproduce
navigate to https://docs.cloudfoundry.org/cf-cli/cf-help.html#buildpacks
<img width="1018" alt="Screen Shot 2020-08-12 at 10 30 49 AM" src="https://user-images.githubusercontent.com/49287206/90027904-0c1acc80-dc87-11ea-8e9c-d0c1cf26570f.png">

Then click "buildpacks" (resolves to: http://cli.cloudfoundry.org/en-US/cf/buildpacks.html)
<img width="992" alt="Screen Shot 2020-08-12 at 10 30 57 AM" src="https://user-images.githubusercontent.com/49287206/90027936-1341da80-dc87-11ea-9b72-cb5267face5b.png">

**Comment by animatedmax** [comment]
Thank you, @jason-upchurch. This issue should now be resolved, and all calls to http://cli.cloudfoundry.org/en-US/cf are directed to http://cli.cloudfoundry.org/en-US/v6/
