### ISSUE TITLE
CLI Installation on windows

### ISSUE THREAD

**Issue by P063978** [cloudfoundry/docs-cf-cli#69]
The installer for the cloud foundry CLI has run apparently successfully, but opening the command prompt as instructed and using the cf command fails. 

C:\Windows\System32>cf
mkdir H:: The system cannot find the path specified.

I am not sure where the mkdir is coming from! Any assistance much appreciated.

**Comment by quixoticmonk** [comment]
@P063978  Have you tried setting an environment variable "CF_HOME" to a directory you have write permissions to ?
I have seen this once and was able to circumvent it this way. 

And, what version of cf cli are you using ?

**Comment by mlimonczenko** [comment]
Hello @P063978,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
