### ISSUE TITLE
Add CLI Version Switching Instructions nav link and new page for TAS v2.7 and above

### ISSUE THREAD

**Issue by heyjcollins** [cloudfoundry/docs-cf-cli#75]
Customers are asking for supported instructions for how to switch between CLI versions on the same computer.
Knowing how to do this reliably is important for users who target different environments during their work.
Some of those environments may be only compatible with the v6 CLI while others are only compatible with the v7 CLI.

The request here is for two things to happen and should be applied to the docs for TAS v2.7 and above.

1) Create a completely new page called "Switching Between Multiple CLI Versions" - the content should be copied from [**this page**](https://github.com/cloudfoundry/cli/wiki/Version-Switching-Guide)
2) Add a new navigational link which points to the new page -  "Switching Between Multiple Versions", on the left nav within the `Using the Cloud Foundry Command Line Interface (cf CLI)` section. I'd suggest placing the link directly below the `Upgrading to cf CLI v7` link.

Lastly - if possible, these changes should also be made to the OSS docs given there's no language or instructions that only pertains to our commercial distribution.

Thanks so much!

if you've got questions, please reach out to me on slack: https://vmware.slack.com/archives/DUATDD5ED

**Comment by mlimonczenko** [comment]
Hello @heyjcollins,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
