### ISSUE TITLE
404 on Experimental Commands Doc

### ISSUE THREAD

**Issue by broxmen** [cloudfoundry/docs-cf-cli#78]
**Describe the bug and the command you saw an issue with**
404 docs on experimental commands like

- [revisions](https://cli.cloudfoundry.org/en-US/v7/revisions.html)
- [revision](https://cli.cloudfoundry.org/en-US/v7/revision.html)
- [rollback](https://cli.cloudfoundry.org/en-US/v7/rollback.html)

**Expected behavior**
Visible docs

**Comment by mlimonczenko** [comment]
Hello @broxmen,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
