### ISSUE TITLE
Installation page doesn't reference CLI v8

### ISSUE THREAD

**Issue by mogul** [cloudfoundry/docs-cf-cli#82]
Although there are reference pages for CLI v8 and documentation about the changes between v7 and v8 in the docs, [the page about installation of the CLI](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html) makes no reference to CLI v8.

**Comment by mjgutermuth** [comment]
Thanks for pointing this out, @mogul! The page now mentions cf CLI v8: https://docs.cloudfoundry.org/cf-cli/install-go-cli.html
